import {firebaseConfig as C} from './config.js';
export const live=!!C.apiKey;
const G='https://www.gstatic.com/firebasejs/10.12.2/';let _f;
export async function fb(){if(!_f){const[a,s]=await Promise.all([import(G+'firebase-app.js'),import(G+'firebase-firestore.js')]);const app=a.initializeApp(C);_f={app,s,db:s.getFirestore(app)}}return _f}
const L={g:(k,d)=>{try{return JSON.parse(localStorage.getItem('snk_'+k))??d}catch{return d}},s:(k,v)=>localStorage.setItem('snk_'+k,JSON.stringify(v))};
const uid=()=>Math.random().toString(36).slice(2,10);
export const DEF={settings:{name:'SNK Support',tagline:'Help when you need it',logo:'',phone:'',website:''},
team:[["shah","Shah Neil Khan","CEO & Founder | Developer","Leads the vision and builds the future. I'm here for technical support, product guidance, and your success."],["nusrat","Nusrat Afsana","Partner & UI Designer","I create beautiful experiences. I'm here for design support, UI/UX advice and creative solutions."],["sakhi","Sakhi Jahan Usha","Co-Founder","Drives the growth and community. I'm here for your queries, guidance and long-term support."],["raihan","Raihan Ahmed","Support Manager","Handles your issues, provides quick solutions, and makes sure you get the best support."],["tanjima","Tanjima Akter","Content Creator","Creates content, shares updates, and keeps you informed. I'm here for your questions and suggestions."]].map(([id,name,role,blurb])=>({id,name,role,blurb,phone:'',photo:''})),
faq:[["reset,password,forgot","On the sign-in page, select “Forgot password?”, enter your email, then open the reset link in your inbox. Check spam if you can't find it."],["started,start,begin,new","Welcome! Create or sign in to your account, complete your profile, then explore the dashboard."],["install,app","Tap “Install App” at the top (or use your browser menu → Add to Home screen)."],["contact,support,help,person,human","Chat or call our team from the Support Team section below."]].map(([k,a],i)=>({id:'f'+i,k,a}))};
export async function getSettings(){if(live){const{s,db}=await fb();const d=await s.getDoc(s.doc(db,'site','settings'));return{...DEF.settings,...(d.exists()?d.data():{})}}return{...DEF.settings,...L.g('settings',{})}}
export async function saveSettings(v){if(live){const{s,db}=await fb();await s.setDoc(s.doc(db,'site','settings'),v)}else L.s('settings',v)}
export async function list(c){if(live){const{s,db}=await fb();const q=await s.getDocs(s.collection(db,c));const r=q.docs.map(d=>({...d.data(),id:d.id}));return r.length?r:DEF[c]}return L.g(c,DEF[c])}
export async function save(c,it){it.id=it.id||uid();if(live){const{s,db}=await fb();await s.setDoc(s.doc(db,c,it.id),it)}else{const a=L.g(c,DEF[c]).slice(),i=a.findIndex(x=>x.id==it.id);i<0?a.push(it):a[i]=it;L.s(c,a)}}
export async function del(c,id){if(live){const{s,db}=await fb();await s.deleteDoc(s.doc(db,c,id))}else L.s(c,L.g(c,DEF[c]).filter(x=>x.id!=id))}
export async function send(sid,m){const t=Date.now();if(live){const{s,db}=await fb();await s.setDoc(s.doc(db,'threads',sid),{sid,member:m.member||'',last:m.text,from:m.from,t},{merge:true});await s.addDoc(s.collection(db,'threads',sid,'msgs'),{from:m.from,text:m.text,t})}else{const T=L.g('threads',{});const h=T[sid]||(T[sid]={sid,msgs:[]});Object.assign(h,{member:m.member||h.member||'',last:m.text,from:m.from,t});h.msgs.push({from:m.from,text:m.text,t});L.s('threads',T)}}
function sub(liveQ,loc,cb){let u=()=>{},off=0;(async()=>{if(live){const{s,db}=await fb();if(!off)u=s.onSnapshot(liveQ(s,db),q=>cb(q.docs.map(d=>d.data())))}else{let p;const f=()=>{const j=JSON.stringify(loc());if(j!=p){p=j;cb(JSON.parse(j))}};f();const i=setInterval(f,800);u=()=>clearInterval(i)}})();return()=>{off=1;u()}}
export const watch=(sid,cb)=>sub((s,db)=>s.query(s.collection(db,'threads',sid,'msgs'),s.orderBy('t')),()=>L.g('threads',{})[sid]?.msgs||[],cb);
export const watchThreads=cb=>sub((s,db)=>s.query(s.collection(db,'threads'),s.orderBy('t','desc')),()=>Object.values(L.g('threads',{})).sort((a,b)=>b.t-a.t),cb);
